// Mock data using only two collections: users and posts.
const nowIso = () => new Date().toISOString();

export const mockUsers = [
  {
    _id: 'u1',
    username: 'john_doe',
    email: 'john@example.com',
    avatar: 'https://i.pravatar.cc/150?img=1',
    firstName: 'John',
    lastName: 'Doe',
    createdAt: nowIso(),
    updatedAt: nowIso(),
  },
  {
    _id: 'u2',
    username: 'jane_smith',
    email: 'jane@example.com',
    avatar: 'https://i.pravatar.cc/150?img=2',
    firstName: 'Jane',
    lastName: 'Smith',
    createdAt: nowIso(),
    updatedAt: nowIso(),
  },
  {
    _id: 'u3',
    username: 'alex_r',
    email: 'alex@example.com',
    avatar: 'https://i.pravatar.cc/150?img=3',
    firstName: 'Alex',
    lastName: 'Rivera',
    createdAt: nowIso(),
    updatedAt: nowIso(),
  },
  {
    _id: 'u4',
    username: 'sam_green',
    email: 'sam@example.com',
    avatar: 'https://i.pravatar.cc/150?img=4',
    firstName: 'Sam',
    lastName: 'Green',
    createdAt: nowIso(),
    updatedAt: nowIso(),
  },
  {
    _id: 'u5',
    username: 'lila_blue',
    email: 'lila@example.com',
    avatar: 'https://i.pravatar.cc/150?img=5',
    firstName: 'Lila',
    lastName: 'Blue',
    createdAt: nowIso(),
    updatedAt: nowIso(),
  },
];

export const mockPosts = [
  {
    _id: 'p1',
    text: 'Just launched my new portfolio website! Check it out.',
    imageUrls: [],
    likes: ['u2', 'u3'],
    comments: [
      {
        _id: 'p1c1',
        text: 'Looks awesome!',
        imageUrls: [],
        likes: ['u1', 'u3'],
        comments: [
          {
            _id: 'p1c1r1',
            text: 'Agreed, super clean.',
            imageUrls: [],
            likes: ['u4'],
            comments: [],
            isComment: true,
            userId: 'u3',
            createdAt: nowIso(),
            updatedAt: nowIso(),
          },
        ],
        isComment: true,
        userId: 'u2',
        createdAt: nowIso(),
        updatedAt: nowIso(),
      },
      {
        _id: 'p1c2',
        text: 'Can you share the tech stack?',
        imageUrls: [],
        likes: ['u5'],
        comments: [],
        isComment: true,
        userId: 'u4',
        createdAt: nowIso(),
        updatedAt: nowIso(),
      },
    ],
    isComment: false,
    userId: 'u1',
    createdAt: nowIso(),
    updatedAt: nowIso(),
  },
  {
    _id: 'p2',
    text: 'Design thinking workshop was amazing today.',
    imageUrls: ['https://images.unsplash.com/photo-1519389950473-47ba0277781c'],
    likes: ['u1', 'u5'],
    comments: [
      {
        _id: 'p2c1',
        text: 'What was your biggest takeaway?',
        imageUrls: [],
        likes: ['u1'],
        comments: [],
        isComment: true,
        userId: 'u3',
        createdAt: nowIso(),
        updatedAt: nowIso(),
      },
    ],
    isComment: false,
    userId: 'u2',
    createdAt: nowIso(),
    updatedAt: nowIso(),
  },
  {
    _id: 'p3',
    text: 'Color study: blending green, yellow, and orange for a fresh UI vibe.',
    imageUrls: ['https://images.unsplash.com/photo-1501004318641-b39e6451bec6'],
    likes: ['u2', 'u4', 'u5'],
    comments: [
      {
        _id: 'p3c1',
        text: 'Palette looks energetic!',
        imageUrls: [],
        likes: ['u1'],
        comments: [
          {
            _id: 'p3c1r1',
            text: 'Agreed, feels summery.',
            imageUrls: [],
            likes: ['u5'],
            comments: [],
            isComment: true,
            userId: 'u2',
            createdAt: nowIso(),
            updatedAt: nowIso(),
          },
        ],
        isComment: true,
        userId: 'u4',
        createdAt: nowIso(),
        updatedAt: nowIso(),
      },
    ],
    isComment: false,
    userId: 'u3',
    createdAt: nowIso(),
    updatedAt: nowIso(),
  },
  {
    _id: 'p4',
    text: 'Sketching mobile nav patterns tonight.',
    imageUrls: [],
    likes: ['u1', 'u3'],
    comments: [
      {
        _id: 'p4c1',
        text: 'Try a pill-shaped bottom bar.',
        imageUrls: [],
        likes: ['u2'],
        comments: [],
        isComment: true,
        userId: 'u5',
        createdAt: nowIso(),
        updatedAt: nowIso(),
      },
      {
        _id: 'p4c2',
        text: 'Add a floating action for quick post.',
        imageUrls: [],
        likes: [],
        comments: [],
        isComment: true,
        userId: 'u3',
        createdAt: nowIso(),
        updatedAt: nowIso(),
      },
    ],
    isComment: false,
    userId: 'u4',
    createdAt: nowIso(),
    updatedAt: nowIso(),
  },
  {
    _id: 'p5',
    text: 'Blue gradients or solid fills for hero sections?',
    imageUrls: [],
    likes: ['u2', 'u3', 'u5'],
    comments: [
      {
        _id: 'p5c1',
        text: 'Gradients feel modern.',
        imageUrls: [],
        likes: ['u1'],
        comments: [],
        isComment: true,
        userId: 'u4',
        createdAt: nowIso(),
        updatedAt: nowIso(),
      },
      {
        _id: 'p5c2',
        text: 'Solid keeps things calm.',
        imageUrls: [],
        likes: ['u3'],
        comments: [
          {
            _id: 'p5c2r1',
            text: 'Maybe blend both with subtle angle.',
            imageUrls: [],
            likes: ['u2'],
            comments: [],
            isComment: true,
            userId: 'u5',
            createdAt: nowIso(),
            updatedAt: nowIso(),
          },
        ],
        isComment: true,
        userId: 'u1',
        createdAt: nowIso(),
        updatedAt: nowIso(),
      },
    ],
    isComment: false,
    userId: 'u5',
    createdAt: nowIso(),
    updatedAt: nowIso(),
  },
];
